[package]
name = "pam-siwe"
version = "0.0.1"
edition = { workspace = true }
resolver = "2"
authors = { workspace = true }
publish = false

[dependencies]
rand = "0.8.5"
fast_qr = "0.11.0"
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"

pam-bindings = { path = "../../submodules/pam-rs/pam" }

walletconnect_sdk = { git = "https://github.com/WalletConnect/WalletConnectRust", rev = "7a205511a98011e4fc0cffb7a3652d435b191cd7" }