[package]
name = "siwe-pam"
version = "0.0.1"
edition = { workspace = true }
resolver = "2"
authors = { workspace = true }
publish = false

[dependencies]
pam-bindings = { path = "../../submodules/pam-rs/pam" }
