on:
  push:
    branches:
      - main
  workflow_call:

name: Build and Test
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          include:
            - os: ubuntu-20.04
              config_args: ""
              packages: "build-essential sudo git curl pkg-config openssl libssl-dev libpam0g-dev llvm-11 clang libclang-dev"
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT}}
      - name: Install Dependencies
        env:
          PACKAGES: ${{ matrix.packages }}
        run: |
          apt-get update && apt-get install -y $PACKAGES
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
          mkdir -p ~/bin
          echo 'export PATH="$PATH:$HOME/bin"' >> ~/.bashrc
      - name: Install the rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build and test pam module
        env:
          CONFIGURE_ARGS: ${{ matrix.config_args }}
        run: |
          source ~/.bashrc
          just install-pam
          just test-pam