on:
  push:
    branches:
      - main
  workflow_call:

name: Build and Test
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          include:
            - os: ubuntu-20.04
              config_args: ""
              packages: ""
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT}}
      - name: Configure AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.13.33.zip" -o "awscliv2.zip" && \
          unzip awscliv2.zip && \
          sudo ./aws/install --update 
          echo -e "${{secrets.AWS_ACCESS_KEY_ID}}\n${{secrets.AWS_SECRET_ACCESS_KEY}}\n${{secrets.AWS_DEFAULT_REGION}}\n" | aws configure
      - name: Install the rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Download dependency cache from S3
        # If the cache doesn't exist in GitHub Artifacts, try S3
        run: aws s3 cp s3://${{vars.S3_BUCKET}}/rust-dependency-cache.tar.gz . && tar -xzf rust-dependency-cache.tar.gz
      - name: Build and test pam module
        env:
          CONFIGURE_ARGS: ${{ matrix.config_args }}
          COMMAND: ${{ vars.COMMAND }}
        run: |
          echo "Running $COMMAND"
          just $COMMAND